import type { Metadata } from 'next'

import { inter } from '@/shared/lib/fonts'
import { MainProvider } from '@/shared/providers'

import './styles/index.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={inter.variable}>
				<MainProvider>{children}</MainProvider>
			</body>
		</html>
	)
}
